export { ReactComponent as IconChecker } from 'assets/icon/darwin/checker.svg';
export { ReactComponent as IconSuccess } from 'assets/icon/darwin/success.svg';
// export { ReactComponent as IconForbidden } from 'assets/icon/darwin/forbidden.svg';
// export { ReactComponent as IconDanger } from 'assets/icon/darwin/danger.svg';
// export { ReactComponent as IconWarning } from 'assets/icon/darwin/warning.svg';
// export { ReactComponent as IconCloud } from 'assets/icon/darwin/cloud.svg';
// export { ReactComponent as IconCompress } from 'assets/icon/darwin/compress.svg';
// export { ReactComponent as IconGear } from 'assets/icon/darwin/gear.svg';
// export { ReactComponent as IconList } from 'assets/icon/darwin/list.svg';
// export { ReactComponent as IconMigrate } from 'assets/icon/darwin/migrate.svg';
// export { ReactComponent as IconPlugin } from 'assets/icon/darwin/plugin.svg';
// export { ReactComponent as IconPrize } from 'assets/icon/darwin/prize.svg';
// export { ReactComponent as IconUninstall } from 'assets/icon/darwin/uninstall.svg';
// export { ReactComponent as IconQuick } from 'assets/icon/darwin/quick.svg';
// export { ReactComponent as IconCustom } from 'assets/icon/darwin/custom.svg';
// export { ReactComponent as IconDoc } from 'assets/icon/darwin/doc.svg';
// export { ReactComponent as IconHelp } from 'assets/icon/darwin/help.svg';
// export { ReactComponent as IconBooks } from 'assets/icon/darwin/books.svg';
// export { ReactComponent as IconJoystick } from 'assets/icon/darwin/joystick.svg';
// export { ReactComponent as IconPackage } from 'assets/icon/darwin/package.svg';
// export { ReactComponent as IconQuestion } from 'assets/icon/darwin/question.svg';
// export { ReactComponent as IconDisk } from 'assets/icon/darwin/disk.svg';
// export { ReactComponent as IconScreen } from 'assets/icon/darwin/screen.svg';
